### ISSUE TITLE
Contracts under `ref/` don't respect `servers` override

### ISSUE THREAD

**Issue by danxmoran** [influxdata/openapi#149]
For example:
* The [`/heath` API in OSS](https://github.com/influxdata/openapi/blob/master/src/oss.yml#L9-L12) is incorrectly generated as [`/api/v2/health`](https://github.com/influxdata/openapi/blob/master/contracts/ref/oss.yml#L2310) in the reference contract.
* The [`/private/legacy/authorizations`](https://github.com/influxdata/openapi/blob/master/src/oss.yml#L27-L38) routes in OSS are incorrectly generated as [`/api/v2/legacy/authorizations`](https://github.com/influxdata/openapi/blob/master/contracts/ref/oss.yml#L2481)

**Comment by jstirnaman** [comment]
related #229
