### ISSUE TITLE
api-reference: Tasks - create a new task

### ISSUE THREAD

**Issue by sunbryely-influxdata** [influxdata/openapi#404]

**Comment by jstirnaman** [comment]
@jeffreyssmith2nd I want to clear this `every` description up. I know you created an issue to make it behave as expected. 
I'm not clear on what "..., depending on the specified time" means here, if anything. Maybe this sentence doesn't belong in the schema at all; it feels more like a description of implementation behavior for `create`, `update`, etc.

https://github.com/influxdata/openapi/blob/4923d26b3b1bf1d0e056f01ba4ba57f8664bec38/src/common/schemas/Task.yml#L34

**Comment by jeffreyssmith2nd** [comment]
I think the `every` description is correct. My guess as to `depending on the specified time` is that the first run will happen sometime after creation, and it will be on the `every` interval. It seems like the intent of that sentence is to make sure people understand that creating the task will not immediately run it.

My issue was specifically around manually forced runs, which has a different schema entirely.
